# use the shared Yast defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-1.24.1_yast_style.yml

AllCops:
  Exclude:
    - '/**/vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 12
