#!/usr/bin/env ruby

dir = File.expand_path("../lib", __FILE__)
$LOAD_PATH.unshift(dir) unless $LOAD_PATH.include?(dir)

require "y2dev/version_bumper"

# require "byebug"; byebug
bumper = Y2Dev::VersionBumper.new(ARGV)
bumper.bump_version



